/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 18-Feb-2020 7:46:01 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Antecedente" CASCADE
;

DROP TABLE IF EXISTS "Carcel" CASCADE
;

DROP TABLE IF EXISTS "Convicto" CASCADE
;

DROP TABLE IF EXISTS "Pena" CASCADE
;

/* Create Tables */

CREATE TABLE "Antecedente"
(
	id_antecedente integer NOT NULL,
	tipo varchar(20) NOT NULL,
	descripcion varchar(200) NOT NULL
)
;

CREATE TABLE "Carcel"
(
	id_carcel integer NOT NULL,
	direccion varchar(100) NOT NULL,
	nombre_carcel varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL
)
;

CREATE TABLE "Convicto"
(
	cedula integer NOT NULL,
	genero varchar(20) NOT NULL,
	nombre varchar(50) NOT NULL,
	apellidos varchar(50) NOT NULL
)
;

CREATE TABLE "Pena"
(
	num_expediente integer NOT NULL,
	fecha_ingreso date NOT NULL,
	fecha_salida date NOT NULL,
	cedula integer NULL,
	id_antecedente integer NULL,
	id_carcel integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Antecedente" ADD CONSTRAINT "PK_Antecedente"
	PRIMARY KEY (id_antecedente)
;

ALTER TABLE "Carcel" ADD CONSTRAINT "PK_Carcel"
	PRIMARY KEY (id_carcel)
;

ALTER TABLE "Convicto" ADD CONSTRAINT "PK_Convicto"
	PRIMARY KEY (cedula)
;

ALTER TABLE "Pena" ADD CONSTRAINT "PK_Pena"
	PRIMARY KEY (num_expediente)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Pena" ADD CONSTRAINT "FK_Pena_Antecedente"
	FOREIGN KEY (id_antecedente) REFERENCES "Antecedente" (id_antecedente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Pena" ADD CONSTRAINT "FK_Pena_Carcel"
	FOREIGN KEY (id_carcel) REFERENCES "Carcel" (id_carcel) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Pena" ADD CONSTRAINT "FK_Pena_Convicto"
	FOREIGN KEY (cedula) REFERENCES "Convicto" (cedula) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Antecedente"
	IS 'Esta tabla contiene los antecedentes de convicto'
;

COMMENT ON TABLE "Carcel"
	IS 'Esta tabla contiene la infomación de la cárcel en la que el convicto paga la pena imputada (Nombre, Ciudad, etc)'
;

COMMENT ON TABLE "Convicto"
	IS 'Esta tabla guarda la información personal del convicto(CC, Nombres, genero, etc)'
;

COMMENT ON TABLE "Pena"
	IS 'Esta tabla contiene la información de la pena que se le imputa al convicto '
;
